export enum Name {
  id = 'id',
  _id = '_id',
  entityId = 'entityId',
  entityTypeId = 'entityTypeId',
  accountId = 'accountId',
  email = 'email',
  password = 'password',
  username = 'username',
  firstName = 'firstName',
  lastName = 'lastName',
  authProviderId = 'authProviderId',
  accountTypeId = 'accountTypeId',
  key = 'key',
  name = 'name',
  params = 'params',
  isValid = 'isValid',
  errors = 'errors',
  hasErrors = 'hasErrors',
  createdTimestamp = 'createdTimestamp',
  updatedTimestamp = 'updatedTimestamp',
  visibilityId = 'visibilityId',
  customClaim = 'customClaim',
}
