name: CI
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
      - '!alpha'
      - '!beta'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'
      - uses: nrwl/nx-set-shas@v3
      - name: Install deps
        run: npm ci
      - name: Lint affected
        run: npx nx affected -t lint
      - name: Test affected
        run: npx firebase emulators:exec --project test "npx nx affected -t test --configuration=ci"
      - name: Build affected
        run: npx nx affected -t build
